language: csharp
mono: none
dotnet: 2.1.300
solution: CrackingTheCodingInterview.sln
install:
  - dotnet restore CrackingTheCodingInterview.sln
script:
  - dotnet build
  - dotnet test Tests/DataStructuresTests/DataStructuresTests.csproj
