language: csharp
mono: none
dotnet: 2.1.300
solution: CrackingTheCodingInterview.sln
install:
  - dotnet restore CrackingTheCodingInterview.sln
  - dotnet install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CrackingTheCodingInterview.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./Tests/DataStructuresTests/bin/Debug/netcoreapp2.1/DataStructuresTests.dll